# Generated by Django 4.1.7 on 2024-10-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_part_price_alter_part_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='part',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
